### PR TITLE
pull request tests

### PR DESCRIPTION
**Pull request by evilfemi**
are we testing this as well.

### CODE REVIEW

**Review by femisimon — COMMENTED** [review]
This looks good

**Review by femisimon — DISMISSED** [review]
foobar needs another line

**Review by evilfemi — COMMENTED** [review]
made the changes requested

**Review by femisimon — CHANGES_REQUESTED** [review]
Make this changes the other one wasn't needed.

**Review by femisimon — APPROVED** [review]

**Review by femisimon — APPROVED** [review]
This LGTM! 👍

**Pull request merged**
